In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import kagglehub
path = kagglehub.dataset_download("brendan45774/test-file")
print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/test-file

In [2]:
import os

os.listdir("/kaggle/input/test-file")

['tested.csv']

In [6]:
import pandas as pd

df = pd.read_csv("/kaggle/input/test-file/tested.csv")

df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [8]:
df['Survived'].value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [12]:
df.groupby('Sex')['Survived'].mean()

Sex
female    1.0
male      0.0
Name: Survived, dtype: float64

In [13]:
df.groupby('Sex')['Survived'].agg(['count', 'sum'])

        count  sum
Sex
female    152  152
male      266    0

In [14]:
df.groupby('Pclass')['Survived'].agg(['count','sum','mean'])

        count  sum      mean
Pclass
1         107   50  0.467290
2          93   30  0.322581
3         218   72  0.330275

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [16]:
df['Age'].describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [20]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [21]:
df['Age'].isnull().sum()

np.int64(0)

In [17]:
df.groupby('Embarked')['Survived'].mean()

Embarked
C    0.392157
Q    0.521739
S    0.325926
Name: Survived, dtype: float64

In [23]:
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df['Fare'].isnull().sum()

np.int64(0)

In [24]:
df.drop(columns=['Cabin'], inplace=True)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [38]:
df.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)
df.columns

KeyError: "['PassengerId', 'Name', 'Ticket'] not found in axis"

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex']) #male=1, female=0;

In [34]:
df['Embarked'] = le.fit_transform(df['Embarked']) # c=0,q=1,s=2

In [35]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  34.5      0      0   7.8292         1
1         1       3    0  47.0      1      0   7.0000         2
2         0       2    1  62.0      0      0   9.6875         1
3         0       3    1  27.0      0      0   8.6625         2
4         1       3    0  22.0      1      1  12.2875         2

In [40]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [49]:
y_pred = model.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

In [51]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[50,  0],
       [ 0, 34]])

In [52]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84